spring:
  #  security:
  #    user:
  #      name: user
  #      password: 8240d31c-b614-45ea-a86b-30459ca203c6
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/spring_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #    username: root
    #    password: 123456
    url: jdbc:mysql://49.234.147.89:3306/spring_study?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: spring_study
    password: wang1234.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
    show-sql: true
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    #    default-property-inclusion: non_null
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true

  logging:
    file: target/app.log
    level:
      ROOT: ERROR
      com.example.demo: TRACE
#      com.example.demo: ERROR
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: "D:\\data\\"





mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.demo

server:
  port: 8081